config:
  experiment_name: "pca_girl_with_sunglasses"
  block: "output_block_4" # the module name of the visualized features (e.g. "output_block_4", "input_block_7").
  experiments_fit: # the list of the experiments to visualize the features for
    - "girl_with_sunglasses"
  experiments_transform: # the list of the experiments used for calculating the principal components
    - "girl_with_sunglasses"
